### ISSUE TITLE
Printing layout problem

### ISSUE THREAD

**Issue by machuvla** [ringomassa/OpenAero#1]
Printing scale and borders are not scaled to have full page printing. 
![screen1](https://cloud.githubusercontent.com/assets/7349024/6960723/3a4876d6-d925-11e4-80e5-0769edba6722.png)

To reproduce: File->Print->Print

Version: 1.5.1.4, browser Chrome 41.0.2272.118 m, Win 7 SP1 x64

Remark: It works perfectly in current devel.openaero.net version 1.5.1.4

**Comment by machuvla** [comment]
Sorry, wrong place to report issue. I've put it into OpenAero/main repo.

**Comment by ringomassa** [comment]
Hi Vladimir,

That is weird, as they are identical, and I don't have the problem.  Could
it have something to do with your print dialog Margins setting?

Regards,
Ringo
 Op 2 apr. 2015 10:45 schreef "Vladimir Machula" notifications@github.com:

**Comment by machuvla** [comment]
Hi Ringo,

I tried multiple margins setting. And actually, friend of mine noticed
this, since it was same for him. Then I realized that it's same problem
for me as well.

Browser restarted, caches flushed. Still the same.

V.

**Comment by ringomassa** [comment]
Hi Vladimir,

That is very annoying. I am flying for KLM now but I'll see if I can find a
solution. Does it also give large margins when saving as PNG?
Op 2 apr. 2015 11:55 schreef "Vladimir Machula" notifications@github.com:

**Comment by machuvla** [comment]
Nope, PNG looks OK. SVG looks OK as well.

Thanks, Vladimir.

**Comment by ringomassa** [comment]
Hi Vladimir,

It suddenly occurred to me you may be using the Chrome app and that is
causing some problem for printing. When you use OpenAero from openaero.net,
do you get it in the regular Chrome window or in a new one without address
bar?

Op donderdag 2 april 2015 heeft Vladimir Machula notifications@github.com
het volgende geschreven:

**Comment by machuvla** [comment]
Working OK when app is uninstalled from browser. Same problem after app
reinstall.

Vladimir.

**Comment by ringomassa** [comment]
OK, thanks. I'll look into the problem with the app this evening.
Op 6 apr. 2015 02:47 schreef "Vladimir Machula" notifications@github.com:

**Comment by ringomassa** [comment]
Hi Vladimir,

Things should finally be working now, with version 1.5.1.5 as app. It might
take a few hours before Chrome retrieves the update. To force this, you
could go to chrome://extensions, select "Developer mode" and click the
"Update extensions now" button.

Could you let me know if it now prints correctly, also on your system from
the app?

By the way, it appears the problem was introduced by a bugfix in Chrome 41.
I was still running on Chrome 40 where it happened to work correctly...

Reagrds,
Ringo

2015-04-06 9:53 GMT+02:00 Ringo Massa ringomassa@gmail.com:

**Comment by machuvla** [comment]
Working smoothly now.

**Comment by machuvla** [comment]
Hi Ringo,

working correctly now in app as well as in browser. Tested.

Interesting with that Chrome bugfix.

Thanks. Vladimir.
